### ISSUE TITLE
porder order --> Bad request

### ISSUE THREAD

**Issue by initze** [samapriya/porder#24]
Hi Samapriya,
running a porder order returns "Failed with response: Bad request".

porder order --name "Peel" --idlist "C:\Users\initze\OneDrive\Paul\imlists\link_file_10.csv" --asset "analytic" --item "PSOrthoTile" --boundary "C:\Users\initze\OneDrive\Paul\peeltour.geojson " --op clip email

The image list was successfully created with porder idlist
After the above error I run a split, which resulted in the same error.

System:
Anaconda virtual environment, python 3.6.3
PL_API_KEY is set
porder quota works

Thanks for your help

**Comment by samapriya** [comment]
Hi @initze 
Issues like this can be best resolved if you post the idlist CSV and GeoJSON file for me to replicate the issue. Look forward to it, in general, a bad request usually refers to issues with Payload.

**Comment by initze** [comment]
Thanks for taking care. Files are attached.
I tried to run the process again about 30 mins ago, but it resulted in the same error.

[initze_badrequest_error.zip](https://github.com/samapriya/porder/files/3222314/initze_badrequest_error.zip)

**Comment by samapriya** [comment]
You are using a multipolygon now depending on the version of porder you have is still experimental in this tool. That being said, I think the problem here is simpler, the configuration of the Multipolygon does not specify multipolygon and this usually creeps in from when you converted it from your kmz file to your geojson file. Try creating and saving a new multipolygon file in geojson and io and replicate the structure from there. The order thing is that all of the footprints do not intersect with a large part of the polygon area.


<img width="811" alt="multipoly_intersect" src="https://user-images.githubusercontent.com/6677629/58437014-12c71f00-8096-11e9-88eb-a949b951afd8.PNG">



Though it is possible that something else might be in the mix, for example, there is a maximum limit of 500 on the number of vertices, and your geometry seems complex as a result of this, the best way to resolve this is to try a simple geometry and see if clip works at your end on that. Then we will be able to narrow down that the issue comes from the geometry. Hope this helps resolve this issue.
