### ISSUE TITLE
can't seem to switch subscriptions

### ISSUE THREAD

**Issue by AndrewAnnex** [samapriya/porder#29]
I am attempting to use a different quota/subscription id using --sid, but I get the following error after submitting orders:

"Quota check failed - Insufficient quota: /subscriptions do not match all of the events"

**Comment by samroy-pl** [comment]
Hi @AndrewAnnex 
Guessing you a  E & R user, you might want to check if you have quota left. Note you have two subscriptions one for PlanetScope and RapidEye data and the other for Landsat.Hence the insufficient quota message because you might be trying to order PlanetScope images using the sid for Landsat and your quota is maxed out.

**Comment by samapriya** [comment]
Hi @AndrewAnnex 
Guessing you a E & R user, you might want to check if you have quota left. Note you have two subscriptions one for PlanetScope and RapidEye data and the other for Landsat.Hence the insufficient quota message because you might be trying to order PlanetScope images using the sid for Landsat and your quota is maxed out.
