### ISSUE TITLE
Missing files after download

### ISSUE THREAD

**Issue by cmehofer76** [samapriya/porder#31]
Hello,

i used porder quite extensively. In some cases, i noticed a strange behaviour regarding the
download: it happened, that certain files from a scene are not downloaded, e.g. the udm file
is missing or the metadata file is missing. If i repeat the download, then the file is loaded.
Sometimes I had to repeat the download more often to get all the files from a scene.
I used "porder download" without arguments and the order was not that big, about 50 scenes.
Do you know something about this problem?

Regards

**Comment by samapriya** [comment]
Hi @cmehofer76 
Glad to know you are using the datasets, and hope you will cite my work. Can you tell me the porder version you have? Version 0.4.0 or higher have this issue fixed because some downloads were hitting the rate limit error and so we introduced a retry function instead of skipping. However, I would recommend updating to the most recent release 0.4.3. Let me know if this solves your problem.

**Comment by samapriya** [comment]
Closing the issue, for now, reopen if the issue persists after upgrade
