### ISSUE TITLE
UDM2 mask download

### ISSUE THREAD

**Issue by cmehofer76** [samapriya/porder#43]
Hello Samapriya,

this is not an issue, but a question: i loaded quite a bit planetscope scenes in summer 2019 (4 band
analytic & analytic_sr product). At this time, i didn't think about the new udm2 mask. Last week, i took a look at these udm2 masks and they look quite promising. So, is it possible to order only the udm2 mask for a planet scene i already have, or is it necessary to order the complete scene (eg bundle type "analytic_sr_udm2") to get the udm2 tif?

Regards
Christian

**Comment by samapriya** [comment]
Hi @cmehofer76 
Great question and I would recommend you raise this question on the [community page](https://support.planet.com/hc/en-us/community/topics) as well. Ordersv2 only allows for you to [download bundles read the bundles reference here](https://developers.planet.com/docs/orders/product-bundles-reference/). Unfortunately downloading only udm2  as an asset does not seem to be an option. You can use the data API to download only the udm2 mask instead of the bundles.
