### ISSUE TITLE
downloading PSScene4Band Analytic

### ISSUE THREAD

**Issue by adampdixon** [samapriya/porder#7]
Hello Sam, I have an education and research grant account, and have access to PSScene4Band in the GUI, and get PSScene4Band in the list of available assets using a curl planet api v1 command, but when using porder (and a list of about 20 items and a clip command):

{"field":null,"general":[{"message":"Order request resulted in no acceptable assets. Likely due to lack of permissions."}]}

I have run a test order using PSOrthoTile which returns successfully, which makes me think there may be an issue with accessing api v2 permissions and porder? Here is my porder command:

porder order --name "allee" --idlist "allee_list1.txt" --item "PSScene4Band" --asset "analytic" --boundary "allee.geojson" --op clip

Thanks for any help or advice.

**Comment by samapriya** [comment]
Here is a couple of my best guess to the possible issue
* Idlist for PSScene4Band and PSOrthoTile are different. I am hoping you ran different idlist for PSScene4Band and PSOrthoTile feel free to attach the idlist in the response
* Also the tool requires the full path to an idlist though I believe that may not be the issue here

A case which I doubt is happening
*   There geometry and the idlist vary largely, feel free to include the allee.geojson as well to test.

**Comment by adampdixon** [comment]
That worked. Your quick feedback was a big help. Thanks. I was using an old PSOrthoTile list and simply failed to notice the difference. I am not using idlist because I am grabbing ids from planet explorer and creating my list to be careful with quota consumption. I should have known to check that though.

**Comment by samapriya** [comment]
Glad it worked, feel free to star the project and cite. Comments help me improve :)

**Comment by adampdixon** [comment]
Will do. The tool is a big help.
